import type { AgentDeskTask, AgentDeskTaskDetail, SessionSummary } from "./types";

const DEMO_PROJECT_ROOT = "/Users/example/work/checkout-service";

function isoHoursFromNow(hours: number): string {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

export const fixtureTasks: AgentDeskTask[] = [
  {
    taskId: "task-20260525-agentdesk-ui",
    title: "Build AgentDesk task queue UI",
    brief:
      "Create a React task management surface that keeps task.md, claims, dispatches, and session history visible.",
    status: "running",
    priority: "urgent",
    scope: "project",
    taskType: "coding",
    projectRoot: DEMO_PROJECT_ROOT,
    createdAt: isoHoursFromNow(-30),
    updatedAt: isoHoursFromNow(-2),
    dueAt: isoHoursFromNow(8),
    tags: ["ui", "task.md", "sessions"],
    subtaskCount: 8,
    completedSubtasks: 5,
    claimedBy: "worker-e",
    activeSessionId: "session-20260525-ui-runtime",
    activeSessionStatus: "running",
    paths: {
      taskMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260525-agentdesk-ui/task.md`,
      memoryMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260525-agentdesk-ui/memory.md`,
    },
  },
  {
    taskId: "task-20260524-local-api",
    title: "Expose local AgentDesk HTTP API",
    brief:
      "Back the web runtime with a Node.js ESM HTTP API and SQLite persistence while preserving MCP stdio behavior.",
    status: "ready",
    priority: "high",
    scope: "project",
    taskType: "coding",
    projectRoot: DEMO_PROJECT_ROOT,
    createdAt: isoHoursFromNow(-52),
    updatedAt: isoHoursFromNow(-6),
    dueAt: isoHoursFromNow(30),
    tags: ["api", "sqlite", "mcp"],
    subtaskCount: 7,
    completedSubtasks: 2,
    paths: {
      taskMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260524-local-api/task.md`,
      memoryMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260524-local-api/memory.md`,
    },
  },
  {
    taskId: "task-20260522-docs-refresh",
    title: "Refresh AgentDesk user docs",
    brief:
      "Document the supported CLI, MCP stdio, web task workflow, and validation expectations without legacy compatibility paths.",
    status: "blocked",
    priority: "normal",
    scope: "project",
    taskType: "coding",
    projectRoot: DEMO_PROJECT_ROOT,
    createdAt: isoHoursFromNow(-88),
    updatedAt: isoHoursFromNow(-18),
    dueAt: isoHoursFromNow(96),
    tags: ["docs", "workflow"],
    subtaskCount: 4,
    completedSubtasks: 1,
    claimedBy: "docs-worker",
    paths: {
      taskMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260522-docs-refresh/task.md`,
      memoryMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260522-docs-refresh/memory.md`,
    },
  },
  {
    taskId: "task-20260518-session-history",
    title: "Audit session history rendering",
    brief:
      "Verify session.md summaries expose subagent reports, last errors, and launch plan metadata for review.",
    status: "succeeded",
    priority: "normal",
    scope: "project",
    taskType: "coding",
    projectRoot: DEMO_PROJECT_ROOT,
    createdAt: isoHoursFromNow(-170),
    updatedAt: isoHoursFromNow(-42),
    dueAt: isoHoursFromNow(250),
    tags: ["sessions", "audit"],
    subtaskCount: 6,
    completedSubtasks: 6,
    paths: {
      taskMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260518-session-history/task.md`,
      memoryMd: `${DEMO_PROJECT_ROOT}/.agent-desk/tasks/task-20260518-session-history/memory.md`,
    },
  },
];

// 额外项目：模拟用户真实工作区（agent-desk 自身 + 另一个示例项目）
const AGENT_DESK_ROOT = "/Users/yanzzp/Documents/CodeProjects/agent-desk";

export const extraDemoTasks: AgentDeskTask[] = [
  {
    taskId: "task-20260520-nav-redesign",
    title: "将 Web UI 改造成项目-任务树模式",
    brief: "参考 Codex / Claude Code 左侧导航，实现可折叠的项目分组 + 任务树 + 专注工作区 + Composer。",
    status: "running",
    priority: "urgent",
    scope: "project",
    taskType: "coding",
    projectRoot: AGENT_DESK_ROOT,
    createdAt: isoHoursFromNow(-20),
    updatedAt: isoHoursFromNow(-1),
    tags: ["ui", "frontend-design", "workspace"],
    subtaskCount: 9,
    completedSubtasks: 4,
    claimedBy: "codex-ui",
    activeSessionId: "session-ui-redesign",
    activeSessionStatus: "running",
    paths: { taskMd: `${AGENT_DESK_ROOT}/.agent-desk/tasks/task-20260520-nav-redesign/task.md` },
  },
  {
    taskId: "task-20260519-tree-component",
    title: "手写 WorkspaceNav 树组件",
    brief: "纯 React + CSS 实现可搜索、可折叠、多项目树，无额外依赖。",
    status: "succeeded",
    priority: "high",
    scope: "project",
    taskType: "coding",
    projectRoot: AGENT_DESK_ROOT,
    createdAt: isoHoursFromNow(-28),
    updatedAt: isoHoursFromNow(-6),
    tags: ["component", "a11y"],
    subtaskCount: 5,
    completedSubtasks: 5,
    paths: { taskMd: `${AGENT_DESK_ROOT}/.agent-desk/tasks/task-20260519-tree-component/task.md` },
  },
  // 另一个示例项目（类似参考图中的「金融分析」）
  {
    taskId: "task-fin-001",
    title: "创建 GitHub 私人仓库并上传分析脚本",
    brief: "为财务循环分析项目初始化远程仓库并同步本地 notebook。",
    status: "ready",
    priority: "normal",
    scope: "project",
    taskType: "coding",
    projectRoot: "/Users/yanzzp/Documents/CodeProjects/financial-analysis",
    createdAt: isoHoursFromNow(-40),
    updatedAt: isoHoursFromNow(-12),
    tags: ["finance", "github"],
    subtaskCount: 4,
    completedSubtasks: 1,
    paths: { taskMd: "/Users/yanzzp/Documents/CodeProjects/financial-analysis/.agent-desk/tasks/task-fin-001/task.md" },
  },
  {
    taskId: "task-fin-002",
    title: "实现循环分析与 AgentDesk 子代理编排",
    brief: "将现有 pandas 分析流程包装成可被 Codex 调用的整体任务。",
    status: "claimed",
    priority: "high",
    scope: "project",
    taskType: "coding",
    projectRoot: "/Users/yanzzp/Documents/CodeProjects/financial-analysis",
    createdAt: isoHoursFromNow(-35),
    updatedAt: isoHoursFromNow(-4),
    tags: ["agent", "loop"],
    subtaskCount: 7,
    completedSubtasks: 3,
    claimedBy: "yanzp",
    paths: { taskMd: "/Users/yanzzp/Documents/CodeProjects/financial-analysis/.agent-desk/tasks/task-fin-002/task.md" },
  },
  // 用户级任务示例
  {
    taskId: "task-user-001",
    title: "整理本周 Codex 技能使用笔记",
    brief: "把最近用到的前端设计、任务编排、验证流程整理成可复用的内部文档。",
    status: "ready",
    priority: "low",
    scope: "user",
    taskType: "general",
    projectRoot: "",
    createdAt: isoHoursFromNow(-10),
    updatedAt: isoHoursFromNow(-2),
    tags: ["notes", "codex"],
    subtaskCount: 3,
    completedSubtasks: 0,
    paths: { taskMd: "~/.agent-desk/tasks/task-user-001/task.md" },
  },
];

export const fixtureSessions: SessionSummary[] = [
  {
    sessionId: "session-20260525-ui-runtime",
    taskId: "task-20260525-agentdesk-ui",
    taskTitle: "Build AgentDesk task queue UI",
    status: "running",
    startedAt: isoHoursFromNow(-3),
    model: "gpt-5.5",
    reasoning: "xhigh",
    serviceTier: "fast",
    parallel: 6,
    launchBatchSize: 6,
    agents: {
      total: 6,
      running: 2,
      succeeded: 3,
      failed: 1,
    },
    lastError: "One worker reported overlapping package.json edits; review before merge.",
  },
  {
    sessionId: "session-20260524-api-design",
    taskId: "task-20260524-local-api",
    taskTitle: "Expose local AgentDesk HTTP API",
    status: "waiting_for_app",
    startedAt: isoHoursFromNow(-10),
    model: "gpt-5.5",
    reasoning: "xhigh",
    serviceTier: "fast",
    parallel: 6,
    launchBatchSize: 6,
    agents: {
      total: 4,
      running: 0,
      succeeded: 0,
      failed: 0,
    },
  },
  {
    sessionId: "session-20260518-history-check",
    taskId: "task-20260518-session-history",
    taskTitle: "Audit session history rendering",
    status: "succeeded",
    startedAt: isoHoursFromNow(-60),
    finishedAt: isoHoursFromNow(-42),
    model: "gpt-5.5",
    reasoning: "xhigh",
    serviceTier: "fast",
    parallel: 6,
    launchBatchSize: 6,
    agents: {
      total: 6,
      running: 0,
      succeeded: 6,
      failed: 0,
    },
  },
];

export function buildFixtureTaskDetail(task: AgentDeskTask): AgentDeskTaskDetail {
  const recentSessions = fixtureSessions.filter((session) => session.taskId === task.taskId);

  return {
    ...task,
    markdown: [
      `# ${task.title}`,
      "",
      "## Goal",
      task.brief,
      "",
      "## Subtasks",
      "- [x] Confirm task.md remains the visible source of work.",
      "- [x] Keep MCP stdio and verunectl as primary interfaces.",
      "- [ ] Validate local HTTP API integration.",
      "- [ ] Record session history after dispatch.",
    ].join("\n"),
    memory: [
      `# Task Memory: ${task.title}`,
      "",
      `- Task ID: ${task.taskId}`,
      `- Project root: ${task.projectRoot}`,
      "- Defaults: gpt-5.5, xhigh, fast, launch batch size 6.",
    ].join("\n"),
    recentSessions,
  };
}
